trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'AICS LSTPSR Service Connection-AICS Bootcamp'
  appName: 'nathan-wk4-bootcamp-webapp'
  resourceGroup: 'bootcamp-Nathan_Yeo-20240808'
  slotName: 'production'
  packagePath: '$(System.DefaultWorkingDirectory)/package.zip'
  runtimeStack: 'NODE|18-lts'
  appSettings: '-Port 3000 -NODE_ENV production'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    NODE_ENV=production PORT=3000 KEY_VAULT_NAME=nathan-wk4-bootcamp node index
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package.zip'
    replaceExistingArchive: true
  displayName: 'Archive project files'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '$(packagePath)'
    runtimeStack: '$(runtimeStack)'
    startUpCommand: 'NODE_ENV=production PORT=3000 KEY_VAULT_NAME=nathan-wk4-bootcamp node index'
    appSettings: '$(appSettings)'
  displayName: 'Deploy to Azure Web App'
